apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend
- frontend
- base
commonLabels:
  app: todoapp
images:
- name: todoapp-backend
  newName: asia-northeast1-docker.pkg.dev/devops-gke-argocd/todoapp-repository/todoapp-backend
  newTag: v1.0.11
- name: todoapp-frontend
  newName: asia-northeast1-docker.pkg.dev/devops-gke-argocd/todoapp-repository/todoapp-frontend
  newTag: v1.0.6
